# version: '4'

# services:
#   redis-master:
#     image: 'bitnami/redis:latest'
#     ports:
#       - '6379:6379'
#     environment:
#       - REDIS_REPLICATION_MODE=master
#       - ALLOW_EMPTY_PASSWORD=yes

#   redis-replica:
#     image: 'bitnami/redis:latest'
#     ports:
#       - '6380:6379'
#     depends_on:
#       - redis-master
#     environment:
#       - REDIS_REPLICATION_MODE=slave
#       - REDIS_MASTER_HOST=redis-master
#       - REDIS_MASTER_PORT_NUMBER=6379
#       - ALLOW_EMPTY_PASSWORD=yes

#   redis-replica-dos:
#     image: 'bitnami/redis:latest'
#     ports:
#       - '6381:6379'
#     depends_on:
#       - redis-master
#     environment:
#       - REDIS_REPLICATION_MODE=slave
#       - REDIS_MASTER_HOST=redis-master
#       - REDIS_MASTER_PORT_NUMBER=6379
#       - ALLOW_EMPTY_PASSWORD=yes

version: '3'

services:
  redis-master:
    image: redis:7.0
    container_name: redis-master
    command: redis-server --port 6379 --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf 


  redis-slave1:
    image: redis:7.0
    container_name: redis-slave1
    command: redis-server --replicaof redis-master 6379 --appendonly yes
    ports:
      - "6380:6379" 
    networks:
      - redis-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf 

  redis-slave2:
    image: redis:7.0
    container_name: redis-slave2
    command: redis-server --replicaof redis-master 6379 --appendonly yes
    ports:
      - "6381:6379" 
    networks:
      - redis-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf 

  redis-sentinel1:
    image: redis:7.0
    container_name: redis-sentinel1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    networks:
      - redis-network
    volumes:
      - ./sentinels.conf:/usr/local/etc/redis/sentinel.conf

  redis-sentinel2:
    image: redis:7.0
    container_name: redis-sentinel2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26380:26380"
    networks:
      - redis-network
    volumes:
      - ./sentinels.conf:/usr/local/etc/redis/sentinel.conf

  redis-sentinel3:
    image: redis:7.0
    container_name: redis-sentinel3
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26381:26381"
    networks:
      - redis-network
    volumes:
      - ./sentinels.conf:/usr/local/etc/redis/sentinel.conf

  # Ocupando 
  redis-distro1:
    image: redis:7.0
    container_name: redis-distro1
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "63782:6379"
    networks:
      - redis-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf 

  edis-distro2:
    image: redis:7.0
    container_name: redis-distro2
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "63783:6379"
    networks:
      - redis-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf 

  redis-distro3:
    image: redis:7.0
    container_name: redis-distro3
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "63784:6379"
    networks:
      - redis-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf 

networks:
  redis-network:
    driver: bridge

volumes:
  redis-master-data:
  redis-slave1-data:
  redis-slave2-data: